OUTPUT_ARCH("riscv")
ENTRY(_start)

MEMORY
{
  RAM (rwx) : ORIGIN = 0x80000000, LENGTH = 128K
}

SECTIONS
{
  . = ORIGIN(RAM);

  .text : {
    *(.text.init)
    *(.text)
    *(.text.*)
  } > RAM

  .rodata : {
    *(.rodata)
    *(.rodata.*)
  } > RAM

  .data : {
    *(.data)
    *(.data.*)
  } > RAM

  .bss : {
    *(.bss)
    *(.bss.*)
    *(COMMON)
  } > RAM

  _end = .;
  PROVIDE(_stack_top = ORIGIN(RAM) + LENGTH(RAM));
}